### PR TITLE
PLANET-2967 Feature/remove more empty git commits

### PR DESCRIPTION
**Pull request by koyan**

### CODE REVIEW

**Comment by koyan** [comment]
Tests done. Test if deployment/autodeployment works for the case where 
[Test 1](https://circleci.com/workflow-run/642a9fdc-9245-416b-9131-9357ae2415cd) there have been no changes in the planet4-nro repo
[Test 2](https://circleci.com/workflow-run/4391d306-b019-461b-8725-56a152df31cd) the original develop deployment included changes in the planet4-nro repo and it still triggered (but this time using a git commit) the next steps.

**Comment by 27Bslash6** [comment]
This doesn't seem to work as intended?

Test: https://circleci.com/gh/greenpeace/planet4-flibble/1279 using a custom built planet4-builder, built on the PR branch of CircleCI.

There are changes in the repository that should carry through but are not respected.

**Comment by koyan** [comment]
I have reviewed the logic. Found why it was not working on that case and have redone it. 
The following tests were done with the latest version of the code:  

a) With changes in the repo (aka git commit needed) it did automatically the following [git commit](https://github.com/greenpeace/planet4-koyansync/commit/9df9008d91f08e4172bcaa8e13f73a6ee8d0fb25). [The CI Job that caused it in develop](https://circleci.com/workflow-run/31ca8bfb-c0ca-41dd-8489-279893148a1d). [And the CI job that was generated](https://circleci.com/workflow-run/8cd0a6e9-952d-4ad9-9b2e-41bedc4474e9) 

b) Without changes to the repo, it [triggered it via api this job](https://circleci.com/workflow-run/2fa96a74-4001-406c-af72-03f9ea81ddc3). This was done with p4-builder:build-264 and it autodeployed to release without commiting to github (But using the api trigger instead)

In all the cases, see the `release-prepare-nro.sh` step of the `prepare-release` job of the develop for full comments of what happened.

**Comment by 27Bslash6** [comment]
✅ Tested: File system changes exist in develop, release does not exist: https://circleci.com/gh/greenpeace/planet4-flibble/1319
✅ Tested: File system changes when release exists: https://circleci.com/gh/greenpeace/planet4-flibble/1326
✅ Tested: Release does not exist: https://circleci.com/gh/greenpeace/planet4-flibble/1338
❌ Tested: Release exists, no further changes: https://github.com/greenpeace/planet4-flibble/commit/b4a8f0607738795e2d91f31d8b4e002a952b6e50 -- should trigger via API as no changes are ready to be committed

**Comment by 27Bslash6** [comment]
* ✅ Release exists, no changes, triggered by re-running the 'prepare' job of develop: https://circleci.com/gh/greenpeace/planet4-flibble/1355
* ✅ Release exists, no changes, re-run entire develop workflow: https://circleci.com/gh/greenpeace/planet4-flibble/1362

**Pull request merged**
