### PR TITLE
Create a p4 python lib to abstract shared python functions

### PR DESCRIPTION
**Pull request by comzeradd**
This adds a p4 libs folder inside the python path (see change in the Dockerfile template).

As a start, this moves shared api and github functions and removes them from the main python scripts.

Other changes:
* Substituted the custom `vprint` method with `print` to make it easier to abstract things, but if we see a value
on storing an artifacts file with all the logs we can figure out a way later that can be re-used by all the python scripts.
* Made `get_pull_request` also return comments endpoint, for cases where we want to post a comment on a PR.
* `get_instance_last_commit_date` renamed to `get_last_commit_date` in order to have a more generic scope.

### CODE REVIEW

**Comment by lithrel** [comment]
Not tested yet but looking good so far, but I think the booking process takes the output of the script as the name of the instance (see https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/58be5d5203a17ac2cf9bab85f99cd64830cb0f0b/.circleci/config.yml#L268) and so using `print` in those functions might break the process ? You could let the original script there and give your new version a different name (or put it in a subfolder) so we have time to modify the other circleci configs

**Comment by comzeradd** [comment]
> I think the booking process takes the output of the script as the name of the instance

Good catch! I amended the code to replace `vprint` with a simple `logs.append`, so we have just one `print` in the end and we can save the logs for debugging.

**Comment by comzeradd** [comment]
It was slightly more complicated than I thought, because even the `print` statements inside `p4.github` are breaking the output. So I removed them for now. We can come up with a more pythonic way of keeping logs, but I think it's fine for now.

I tested with [this PR](https://github.com/greenpeace/planet4-master-theme/pull/1414) and seems to [work fine](https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/3536/workflows/690bcfb7-6a71-4894-b7dd-ca3d6b5087f8).

**Review by lithrel — APPROVED** [review]
:+1:

**Pull request merged**
